== Karaf Camel Log QuickStart

This quickstart shows a simple Apache Camel application that logs a message to the server log every second.

This example is implemented using solely the XML DSL (there is no Java code). The source code is provided in the following XML file `src/main/resources/OSGI-INF/blueprint/camel-log.xml`.
It also shows how Karaf assembly files can be overridden using resources from `src/main/resources/assembly/`. The included sample log file `etc/org.ops4j.pax.logging.cfg` sets the log level to DEBUG.

IMPORTANT: This quickstart can run in 1 mode: on Kubernetes / OpenShift Cluster

== Running the Quickstart on a single-node Kubernetes/OpenShift cluster

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

To deploy this quickstart to a running single-node OpenShift cluster:

. Download the project and extract the archive on your local filesystem.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/spring-boot-camel`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/karaf-camel-log
----

. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests fabric8:deploy -Popenshift
----

. List all the running pods:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get pods
----

. Find the name of the pod that runs this quickstart. Output the logs from the running pods and see the messages sent by Camel:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc logs <name of pod>
----

